# Generated by Django 4.2.5 on 2023-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='albums',
        ),
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(default='#', upload_to=''),
        ),
    ]
