# Generated by Django 4.2.5 on 2023-09-28 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='lastorder',
            field=models.FloatField(default=10.1, max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='s_contact',
            field=models.EmailField(default='email@supplier.com', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='s_website',
            field=models.URLField(default='www.supplier.com'),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
